# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate BackendFlightOracle.kt: the backend's own ball flights and club priors (plan F2b).

Plan F2b flies every drawn and measured shot with the backend's aerodynamics (the Ferguson,
McNally & McPhee 2022 polynomials with 0.04/s spin decay). This script records what the *backend*
simulator (`openflight.ballistics.simulate`) says a set of launches does at sea level (1.225):
carry, apex, lateral, landing angle, flight time and landing spin. It also dumps `CLUB_PHYSICS`,
so the Kotlin tests can assert the app's flight stays within 0.5 % of the backend and its per-club
priors are the backend's.

Run against a checkout of the backend (github.com/btripp/openflight, pinned in plans §0.1) from the
repo root:

    PYTHONPATH=<backend>/src uv run --no-project --with pyserial \
        python core/flight/tools/gen_flight_oracle.py <backend> \
        > core/flight/src/commonTest/kotlin/dev/openflight/companion/core/flight/BackendFlightOracle.kt

`pyserial` is only needed because the backend's package `__init__` imports its radar driver.
Then run `./gradlew spotlessApply`.
"""

import datetime
import subprocess
import sys

from openflight import ballistics
from openflight.clubs import ClubType
from openflight.clubs.physics import CLUB_PHYSICS

# name, club wire value, ball speed (mph), launch (deg), spin (rpm), spin axis (deg)
LAUNCHES = [
    # The backend's own amateur priors (CLUB_PHYSICS), as BackendDensityOracle uses.
    ("AMATEUR_DRIVER", "driver", 143.0, 11.0, 2700.0, 0.0),
    ("AMATEUR_SEVEN_IRON", "7-iron", 100.0, 20.5, 6500.0, 0.0),
    ("AMATEUR_PITCHING_WEDGE", "pw", 82.0, 28.0, 9000.0, 0.0),
    # TrackMan 2009 PGA Tour average launches (see TrackManTourAverages.kt).
    ("TOUR_DRIVER", "driver", 165.0, 11.2, 2685.0, 0.0),
    ("TOUR_SEVEN_IRON", "7-iron", 120.0, 16.3, 7097.0, 0.0),
    ("TOUR_PITCHING_WEDGE", "pw", 102.0, 24.2, 9304.0, 0.0),
    # Curve: a 10° spin axis (fade) on the tour driver and 7-iron.
    ("TOUR_DRIVER_AXIS_10", "driver", 165.0, 11.2, 2685.0, 10.0),
    ("TOUR_SEVEN_IRON_AXIS_10", "7-iron", 120.0, 16.3, 7097.0, 10.0),
]

WIRE = {
    ClubType.DRIVER: "driver",
    ClubType.WOOD_3: "3-wood",
    ClubType.WOOD_5: "5-wood",
    ClubType.WOOD_7: "7-wood",
    ClubType.HYBRID_3: "3-hybrid",
    ClubType.HYBRID_5: "5-hybrid",
    ClubType.HYBRID_7: "7-hybrid",
    ClubType.HYBRID_9: "9-hybrid",
    ClubType.IRON_2: "2-iron",
    ClubType.IRON_3: "3-iron",
    ClubType.IRON_4: "4-iron",
    ClubType.IRON_5: "5-iron",
    ClubType.IRON_6: "6-iron",
    ClubType.IRON_7: "7-iron",
    ClubType.IRON_8: "8-iron",
    ClubType.IRON_9: "9-iron",
    ClubType.PW: "pw",
    ClubType.GW: "gw",
    ClubType.SW: "sw",
    ClubType.LW: "lw",
    ClubType.UNKNOWN: "unknown",
}


def main():
    backend = sys.argv[1] if len(sys.argv) > 1 else "."
    commit = subprocess.check_output(["git", "-C", backend, "rev-parse", "HEAD"], text=True).strip()
    commit_date = subprocess.check_output(
        ["git", "-C", backend, "show", "-s", "--format=%cs", "HEAD"], text=True
    ).strip()

    print("// SPDX-License-Identifier: AGPL-3.0-or-later")
    print("package dev.openflight.companion.core.flight")
    print()
    print("/**")
    print(" * Generated by `core/flight/tools/gen_flight_oracle.py`; don't edit by hand. The backend's")
    print(" * `ballistics.simulate()` flights at sea level (1.225) and its `CLUB_PHYSICS` priors.")
    print(f" * Backend commit `{commit}` ({commit_date}), generated {datetime.date.today().isoformat()}.")
    print(" */")
    print("internal object BackendFlightOracle {")
    print(f'    const val BACKEND_COMMIT = "{commit}"')
    print(f"    const val AIR_DENSITY = {ballistics.AIR_DENSITY_STD}")
    print()
    print("    data class Flight(")
    print("        val name: String,")
    print("        val club: String,")
    print("        val ballSpeedMph: Double,")
    print("        val launchDegrees: Double,")
    print("        val spinRpm: Double,")
    print("        val spinAxisDegrees: Double,")
    print("        val carryYards: Double,")
    print("        val apexYards: Double,")
    print("        val lateralYards: Double,")
    print("        val landingAngleDegrees: Double,")
    print("        val flightTimeSeconds: Double,")
    print("        val landingSpinRpm: Double,")
    print("    )")
    print()
    print("    data class Physics(")
    print("        val club: String,")
    print("        val optimalLaunchDegrees: Double,")
    print("        val averageBallSpeedMph: Double,")
    print("        val launchDegreesPerMph: Double,")
    print("        val typicalSpinRpm: Double,")
    print("    )")
    print()
    print("    val flights =")
    print("        listOf(")
    for name, club, speed, launch, spin, axis in LAUNCHES:
        conditions = ballistics.LaunchConditions(
            ball_speed_mph=speed,
            launch_angle_v=launch,
            launch_angle_h=0.0,
            spin_rpm=spin,
            spin_axis_deg=axis,
            spin_source="measured",
        )
        t = ballistics.simulate(conditions)
        print("            Flight(")
        print(f'                name = "{name}",')
        print(f'                club = "{club}",')
        print(f"                ballSpeedMph = {speed},")
        print(f"                launchDegrees = {launch},")
        print(f"                spinRpm = {spin},")
        print(f"                spinAxisDegrees = {axis},")
        print(f"                carryYards = {t.carry_yards:.4f},")
        print(f"                apexYards = {t.apex_yards:.4f},")
        print(f"                lateralYards = {t.lateral_yards:.4f},")
        print(f"                landingAngleDegrees = {t.landing_angle_deg:.4f},")
        print(f"                flightTimeSeconds = {t.flight_time_s:.4f},")
        print(f"                landingSpinRpm = {t.points[-1].spin_rpm:.2f},")
        print("            ),")
    print("        )")
    print()
    print("    val clubPhysics =")
    print("        listOf(")
    for club_type, physics in CLUB_PHYSICS.items():
        print(
            f'            Physics("{WIRE[club_type]}", {float(physics.optimal_launch_deg)}, '
            f"{float(physics.average_ball_speed_mph)}, {float(physics.launch_deg_per_mph)}, "
            f"{float(physics.typical_spin_rpm)}),"
        )
    print("        )")
    print("}")


if __name__ == "__main__":
    main()
