# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate BackendDensityOracle.kt: the backend's own air-density carry ratios (plan F2, §0.2).

The app's conditions adjustment is a ratio from our simulator applied to the server's carry.
This script records what the *backend* simulator (`openflight.ballistics.simulate`) says the
same ratio is, so the Kotlin test can assert the app stays within 1% of it.

Run against a checkout of the backend (github.com/btripp/openflight, pinned in plans §0.1) from the
repo root:

    PYTHONPATH=<backend>/src uv run --no-project --with pyserial \
        python core/flight/tools/gen_density_oracle.py <backend> \
        > core/flight/src/commonTest/kotlin/dev/openflight/companion/core/flight/BackendDensityOracle.kt

`pyserial` is only needed because the backend's package `__init__` imports its radar driver.
Then run `./gradlew spotlessApply` (the output is already formatted close to the house style).
"""

import datetime
import math
import subprocess
import sys

from openflight import ballistics
from openflight.clubs import ClubType
from openflight.clubs.physics import CLUB_PHYSICS

# Dry-air density from the ISA barometric formula; the same formula AirDensity.kt implements.
# The Kotlin test uses these densities directly, so it checks the aero model, not this formula.
R_DRY = 287.05  # J/(kg·K)
P0_PA = 101325.0
ALTITUDE_M = 1609.0  # Denver, one mile


def pressure_pa(altitude_m):
    return P0_PA * (1.0 - 2.25577e-5 * altitude_m) ** 5.25588


def density(altitude_m, temperature_c):
    return pressure_pa(altitude_m) / (R_DRY * (temperature_c + 273.15))


DENSITIES = [
    ("MILE_HIGH_15C", density(ALTITUDE_M, 15.0)),
    ("MILE_HIGH_ISA", density(ALTITUDE_M, 15.0 - 0.0065 * ALTITUDE_M)),
]

# The backend's own per-club defaults (clubs/physics.py): average amateur ball speed, baseline
# launch, and the TrackMan PGA Tour typical spin the backend falls back to.
LAUNCHES = [
    ("DRIVER", "driver", CLUB_PHYSICS[ClubType.DRIVER]),
    ("SEVEN_IRON", "7-iron", CLUB_PHYSICS[ClubType.IRON_7]),
    ("PITCHING_WEDGE", "pw", CLUB_PHYSICS[ClubType.PW]),
]


def main():
    backend = sys.argv[1] if len(sys.argv) > 1 else "."
    commit = subprocess.check_output(["git", "-C", backend, "rev-parse", "HEAD"], text=True).strip()
    commit_date = subprocess.check_output(
        ["git", "-C", backend, "show", "-s", "--format=%cs", "HEAD"], text=True
    ).strip()

    print("// SPDX-License-Identifier: AGPL-3.0-or-later")
    print("package dev.openflight.companion.core.flight")
    print()
    print("/**")
    print(" * Generated by `core/flight/tools/gen_density_oracle.py`; don't edit by hand. The backend's")
    print(" * `ballistics.simulate(..., air_density=)` carry ratios (mile-high / sea level 1.225).")
    print(f" * Backend commit `{commit}` ({commit_date}), generated {datetime.date.today().isoformat()}.")
    print(" */")
    print("internal object BackendDensityOracle {")
    print(f'    const val BACKEND_COMMIT = "{commit}"')
    print(f"    const val SEA_LEVEL_DENSITY = {ballistics.AIR_DENSITY_STD}")
    for name, rho in DENSITIES:
        print(f"    const val {name}_DENSITY = {rho:.6f}")
    print()
    print("    data class Case(")
    print("        val name: String,")
    print("        val club: String,")
    print("        val ballSpeedMph: Double,")
    print("        val launchDegrees: Double,")
    print("        val spinRpm: Double,")
    print("        val density: Double,")
    print("        val seaLevelCarryYards: Double,")
    print("        val carryRatio: Double,")
    print("    )")
    print()
    print("    val cases =")
    print("        listOf(")
    for launch_name, club, physics in LAUNCHES:
        conditions = ballistics.LaunchConditions(
            ball_speed_mph=physics.average_ball_speed_mph,
            launch_angle_v=physics.optimal_launch_deg,
            launch_angle_h=0.0,
            spin_rpm=physics.typical_spin_rpm,
            spin_axis_deg=0.0,
            spin_source="club_typical",
        )
        sea_level = ballistics.simulate(conditions).carry_yards
        for density_name, rho in DENSITIES:
            ratio = ballistics.simulate(conditions, air_density=rho).carry_yards / sea_level
            print("            Case(")
            print(f'                name = "{launch_name} @ {density_name}",')
            print(f'                club = "{club}",')
            print(f"                ballSpeedMph = {float(physics.average_ball_speed_mph)},")
            print(f"                launchDegrees = {float(physics.optimal_launch_deg)},")
            print(f"                spinRpm = {float(physics.typical_spin_rpm)},")
            print(f"                density = {density_name}_DENSITY,")
            print(f"                seaLevelCarryYards = {sea_level:.4f},")
            print(f"                carryRatio = {ratio:.6f},")
            print("            ),")
    print("        )")
    print("}")


if __name__ == "__main__":
    main()
