// SPDX-License-Identifier: AGPL-3.0-or-later
package dev.openflight.companion.core.flight

import assertk.assertThat
import assertk.assertions.isBetween
import assertk.assertions.isEqualTo
import assertk.assertions.isLessThan
import dev.openflight.companion.core.flight.FlightGoldens.apexYards
import dev.openflight.companion.core.flight.FlightGoldens.carryYards
import dev.openflight.companion.core.flight.FlightGoldens.landingAngleDegrees
import dev.openflight.companion.core.flight.FlightGoldens.lateralYards
import kotlin.math.abs
import kotlin.test.Test

/**
 * Plan F2b: the render model flies the backend's own `ballistics.simulate()` flights
 * ([BackendFlightOracle], generated by `core/flight/tools/gen_flight_oracle.py` against the pinned
 * backend) within 0.5 %, and its per-club priors are the backend's `CLUB_PHYSICS`.
 */
class BackendFlightOracleTest {
    private fun fly(flight: BackendFlightOracle.Flight): FlightTrajectory =
        FlightGoldens.unconstrained.simulate(
            FlightGoldens.input(
                ballSpeedMph = flight.ballSpeedMph,
                launchDegrees = flight.launchDegrees,
                spinRpm = flight.spinRpm,
                spinAxisDegrees = flight.spinAxisDegrees,
            ),
        )

    private fun relative(
        app: Double,
        backend: Double,
    ) = abs(app / backend - 1.0)

    @Test
    fun flightsMatchTheBackendWithinHalfAPercent() {
        assertThat(BackendFlightOracle.AIR_DENSITY).isEqualTo(BallFlightSimulator.Configuration.render.airDensity)
        for (flight in BackendFlightOracle.flights) {
            val app = fly(flight)
            println(
                "backend ${flight.name}: carry ${app.carryYards}/${flight.carryYards} apex ${app.apexYards}/" +
                    "${flight.apexYards} land ${app.landingAngleDegrees}/${flight.landingAngleDegrees} " +
                    "T ${app.flightTime}/${flight.flightTimeSeconds} lat ${app.lateralYards}/${flight.lateralYards}",
            )

            assertThat(relative(app.carryYards, flight.carryYards), "carry ${flight.name}").isLessThan(0.005)
            assertThat(relative(app.apexYards, flight.apexYards), "apex ${flight.name}").isLessThan(0.005)
            assertThat(relative(app.landingAngleDegrees, flight.landingAngleDegrees), "land ${flight.name}")
                .isLessThan(0.005)
            assertThat(relative(app.flightTime, flight.flightTimeSeconds), "time ${flight.name}").isLessThan(0.005)
            assertThat(relative(app.landingSpinRpm ?: 0.0, flight.landingSpinRpm), "spin ${flight.name}")
                .isLessThan(0.005)
            if (flight.spinAxisDegrees != 0.0) {
                assertThat(relative(app.lateralYards, flight.lateralYards), "lateral ${flight.name}").isLessThan(0.005)
            }
        }
    }

    @Test
    fun aDrawnShotAnchoredToTheBackendCarryNeedsNoDragFudge() {
        for (flight in BackendFlightOracle.flights) {
            val input =
                FlightGoldens.input(
                    ballSpeedMph = flight.ballSpeedMph,
                    launchDegrees = flight.launchDegrees,
                    spinRpm = flight.spinRpm,
                    spinAxisDegrees = flight.spinAxisDegrees,
                    targetCarryYards = flight.carryYards,
                )
            val fit = checkNotNull(FlightGoldens.render.simulate(input).carryFit)

            // The server's carry_spin_adjusted is this simulation, so k ≈ 1 by construction.
            assertThat(fit.dragScale, flight.name).isBetween(0.97, 1.03)
        }
    }

    @Test
    fun clubPriorsAreTheBackendsClubPhysics() {
        for (physics in BackendFlightOracle.clubPhysics) {
            val app = ClubPhysics.forClub(physics.club)

            assertThat(app.optimalLaunchDegrees, physics.club).isEqualTo(physics.optimalLaunchDegrees)
            assertThat(app.averageBallSpeedMph, physics.club).isEqualTo(physics.averageBallSpeedMph)
            assertThat(app.launchDegreesPerMph, physics.club).isEqualTo(physics.launchDegreesPerMph)
            assertThat(app.typicalSpinRpm, physics.club).isEqualTo(physics.typicalSpinRpm)
        }
    }
}
