// SPDX-License-Identifier: AGPL-3.0-or-later
package dev.openflight.companion.core.flight

/**
 * Generated by `core/flight/tools/gen_density_oracle.py`; don't edit by hand. The backend's
 * `ballistics.simulate(..., air_density=)` carry ratios (mile-high / sea level 1.225).
 * Backend commit `7ca4b409aa4929f0b5de17ee2699adf1f636bf8a` (2026-09-23), generated 2026-09-25.
 */
internal object BackendDensityOracle {
    const val BACKEND_COMMIT = "7ca4b409aa4929f0b5de17ee2699adf1f636bf8a"
    const val SEA_LEVEL_DENSITY = 1.225
    const val MILE_HIGH_15C_DENSITY = 1.008676
    const val MILE_HIGH_ISA_DENSITY = 1.046665

    data class Case(
        val name: String,
        val club: String,
        val ballSpeedMph: Double,
        val launchDegrees: Double,
        val spinRpm: Double,
        val density: Double,
        val seaLevelCarryYards: Double,
        val carryRatio: Double,
    )

    val cases =
        listOf(
            Case(
                name = "DRIVER @ MILE_HIGH_15C",
                club = "driver",
                ballSpeedMph = 143.0,
                launchDegrees = 11.0,
                spinRpm = 2700.0,
                density = MILE_HIGH_15C_DENSITY,
                seaLevelCarryYards = 224.6162,
                carryRatio = 1.031520,
            ),
            Case(
                name = "DRIVER @ MILE_HIGH_ISA",
                club = "driver",
                ballSpeedMph = 143.0,
                launchDegrees = 11.0,
                spinRpm = 2700.0,
                density = MILE_HIGH_ISA_DENSITY,
                seaLevelCarryYards = 224.6162,
                carryRatio = 1.027616,
            ),
            Case(
                name = "SEVEN_IRON @ MILE_HIGH_15C",
                club = "7-iron",
                ballSpeedMph = 100.0,
                launchDegrees = 20.5,
                spinRpm = 6500.0,
                density = MILE_HIGH_15C_DENSITY,
                seaLevelCarryYards = 132.6196,
                carryRatio = 1.072526,
            ),
            Case(
                name = "SEVEN_IRON @ MILE_HIGH_ISA",
                club = "7-iron",
                ballSpeedMph = 100.0,
                launchDegrees = 20.5,
                spinRpm = 6500.0,
                density = MILE_HIGH_ISA_DENSITY,
                seaLevelCarryYards = 132.6196,
                carryRatio = 1.059812,
            ),
            Case(
                name = "PITCHING_WEDGE @ MILE_HIGH_15C",
                club = "pw",
                ballSpeedMph = 82.0,
                launchDegrees = 28.0,
                spinRpm = 9000.0,
                density = MILE_HIGH_15C_DENSITY,
                seaLevelCarryYards = 101.2811,
                carryRatio = 1.055829,
            ),
            Case(
                name = "PITCHING_WEDGE @ MILE_HIGH_ISA",
                club = "pw",
                ballSpeedMph = 82.0,
                launchDegrees = 28.0,
                spinRpm = 9000.0,
                density = MILE_HIGH_ISA_DENSITY,
                seaLevelCarryYards = 101.2811,
                carryRatio = 1.045920,
            ),
        )
}
