// SPDX-License-Identifier: AGPL-3.0-or-later
package dev.openflight.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension

/**
 * Turns every `*.json` file under [fixtures] into a string constant of one generated Kotlin
 * `object`, so `commonTest` can read committed fixture files on every target (the Android host
 * and the iOS simulator have no shared resource loader). The files stay the source of truth:
 * refresh them and the next build regenerates the object.
 */
@CacheableTask
abstract class GenerateJsonFixturesTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val fixtures: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val objectName: Property<String>

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val root = fixtures.get().asFile
        val files =
            root
                .walkTopDown()
                .filter { it.isFile && it.extension == "json" }
                .sortedBy { it.relativeTo(root).invariantSeparatorsPath }
                .toList()
        val entries =
            files.joinToString(separator = "") { file ->
                val key = file.relativeTo(root).invariantSeparatorsPath.removeSuffix(".json")
                "        \"${key.escapeKotlin()}\" to \"${file.readText().escapeKotlin()}\",\n"
            }
        val source =
            buildString {
                append("// Generated by GenerateJsonFixturesTask from ${root.name}/. Do not edit.\n")
                append("package ${packageName.get()}\n\n")
                append("internal object ${objectName.get()} {\n")
                append("    /** File path relative to the fixture directory, without `.json` -> file contents. */\n")
                append("    val files: Map<String, String> = mapOf(\n")
                append(entries)
                append("    )\n")
                append("}\n")
            }
        val output = outputDirectory.get().asFile
        output.deleteRecursively()
        val target = output.resolve(packageName.get().replace('.', '/')).resolve("${objectName.get()}.kt")
        target.parentFile.mkdirs()
        target.writeText(source)
    }
}

private fun String.escapeKotlin(): String =
    buildString {
        for (char in this@escapeKotlin) {
            when (char) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '$' -> append("\\$")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(char)
            }
        }
    }

/**
 * Generates `objectName` in `packageName` from the JSON files under [fixtureDir] (relative to the
 * project) and adds it to `commonTest`.
 */
fun Project.commonTestJsonFixtures(
    fixtureDir: Any,
    packageName: String,
    objectName: String,
) {
    val task =
        tasks.register("generate$objectName", GenerateJsonFixturesTask::class.java) {
            fixtures.set(file(fixtureDir))
            this.packageName.set(packageName)
            this.objectName.set(objectName)
            outputDirectory.set(layout.buildDirectory.dir("generated/jsonFixtures/$objectName"))
        }
    extensions.getByType(KotlinMultiplatformExtension::class.java).sourceSets.getByName("commonTest") {
        kotlin.srcDir(task.flatMap { it.outputDirectory })
    }
}
