// SPDX-License-Identifier: AGPL-3.0-or-later
package dev.openflight.companion.core.protocol

import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test

/**
 * Cross-language golden test: the Kotlin encoder must produce byte-identical BLE frames to the
 * authoritative Python encoder in `src/openflight/ble/protocol.py`.
 *
 * These frames were generated by `tools/gen-frame-goldens.py` against the reference repo's
 * `protocol.py` and the shared contract fixture `ios/OpenFlightTests/Fixtures/shot_v1.json`,
 * compacted with `sort_keys`, at `sequence=0x0102`:
 *
 * ```
 * uv run --no-project python tools/gen-frame-goldens.py \
 *     --protocol "$REF/src/openflight/ble/protocol.py" \
 *     --fixture "$REF/ios/OpenFlightTests/Fixtures/shot_v1.json"
 * ```
 */
class GoldenFrameTest {
    @Test
    fun kotlinEncoderProducesByteIdenticalFramesToThePythonEncoder() {
        val payload = compactSortedJson(SHOT_V1_FIXTURE_JSON)

        val frames = BleFrameEncoder.frames(payload, sequence = GOLDEN_SEQUENCE)
        val actualHex = frames.map { it.toHex() }

        assertThat(actualHex).isEqualTo(GOLDEN_FRAME_HEX)
    }

    @Test
    fun theReassemblerRoundTripsTheGoldenFrames() {
        val payload = compactSortedJson(SHOT_V1_FIXTURE_JSON)
        val reassembler = BleFrameReassembler()

        var result: ByteArray? = null
        for (hex in GOLDEN_FRAME_HEX) {
            result = reassembler.append(hex.hexToByteArray()) ?: result
        }

        assertThat(result!!.toList()).isEqualTo(payload.toList())
    }

    private companion object {
        const val GOLDEN_SEQUENCE = 0x0102

        // Reproduces protocol.encode_shot_event's exact serialization: compact separators,
        // ensure_ascii, and sort_keys -- the same bytes the golden script fed to fragment_payload.
        fun compactSortedJson(fixtureJson: String): ByteArray {
            val json = OpenFlightJson.parseToJsonElement(fixtureJson.trim())
            val sorted = sortJsonObjectKeys(json)
            return OpenFlightJson
                .encodeToString(
                    kotlinx.serialization.json.JsonElement
                        .serializer(),
                    sorted,
                ).encodeToByteArray()
        }

        fun sortJsonObjectKeys(
            element: kotlinx.serialization.json.JsonElement,
        ): kotlinx.serialization.json.JsonElement =
            when (element) {
                is kotlinx.serialization.json.JsonObject -> {
                    val sorted = LinkedHashMap<String, kotlinx.serialization.json.JsonElement>()
                    for (key in element.keys.sorted()) {
                        sorted[key] = sortJsonObjectKeys(element.getValue(key))
                    }
                    kotlinx.serialization.json.JsonObject(sorted)
                }

                is kotlinx.serialization.json.JsonArray -> {
                    kotlinx.serialization.json.JsonArray(element.map { sortJsonObjectKeys(it) })
                }

                else -> {
                    element
                }
            }

        fun ByteArray.toHex(): String =
            joinToString("") { byte -> ((byte.toInt() and 0xFF) + 0x100).toString(16).substring(1) }

        fun String.hexToByteArray(): ByteArray =
            ByteArray(
                length / 2,
            ) { i -> ((this[i * 2].digitToInt(16) shl 4) or this[i * 2 + 1].digitToInt(16)).toByte() }

        // Generated 2026-09-24 with tools/gen-frame-goldens.py; payload = 338 bytes, 23 frames.
        val GOLDEN_FRAME_HEX =
            listOf(
                "01010200177b2262616c6c5f73706565645f6d70",
                "010102011768223a3135312e342c22636c756222",
                "01010202173a22647269766572222c22636c7562",
                "01010203175f706174685f646567223a322e312c",
                "010102041722636c75625f73706565645f6d7068",
                "0101020517223a3130332e322c22657374696d61",
                "01010206177465645f63617272795f7961726473",
                "0101020717223a3236342c226576656e745f6964",
                "0101020817223a2242304439314630412d373935",
                "0101020917302d344437452d394444352d414639",
                "0101020a17373737433139304531222c226c6175",
                "0101020b176e63685f616e676c655f686f72697a",
                "0101020c176f6e74616c223a2d312e332c226c61",
                "0101020d17756e63685f616e676c655f76657274",
                "0101020e176963616c223a31322e362c22736368",
                "0101020f17656d615f76657273696f6e223a312c",
                "010102101722736d6173685f666163746f72223a",
                "0101021117312e34372c227370696e5f61786973",
                "01010212175f646567223a2d332e342c22737069",
                "01010213176e5f72706d223a323338302c227469",
                "01010214176d657374616d70223a22323032362d",
                "010102151730372d32395431393a34323a31302e",
                "0101021617313233343536227d",
            )
    }
}
